### ISSUE TITLE
Footer is covering button.

### ISSUE THREAD

**Issue by HabibUrRehmanBhattii** [hmjatt/Quizzical#3]
When its in mobile view the the footer is over the button. You can set z-index to -1.

**Comment by hmjatt** [comment]
Just pushed a PR that fixes this issue, there is some extra scroll space on mobile sometimes if the content is smaller than fixed view height. But rather than that it works fine. Also, fixed the check answers button and the result section, it's little bit more spacious. Looking forward to your feedback when you get a chance.

**Comment by HabibUrRehmanBhattii** [comment]
https://rainbow-meerkat-4faba0.netlify.app/

what do you think about this

**Comment by hmjatt** [comment]
I think that's going to work even better as it gets rid of the extra scroll space. Two birds with one stone lol

**Comment by HabibUrRehmanBhattii** [comment]
Okay i am creating PR but you have rework on readme.md

**Comment by hmjatt** [comment]
okay sounds good
